apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  selector:
    app: weather-app
  ports:
   - protocol: TCP
     port: 80
     targetPort: 5000      # you can see it by minikube ssh > curl localhost:80
  type: ClusterIP
# apiVersion: v1
# kind: Service
# metadata:
#   name: weather-app
# spec:
#   selector:
#     app: weather-app
#   ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 5000
#      nodePort: 30080  # Port on each node where the service will be exposed you can see it by minikube_ip:30080
#   type: NodePort
